#pragma once
#ifndef WS_COMPENENT_HEADERS_H
#define WS_COMPENENT_HEADERS_H
#include "Transform2D.h"
#include "SpriteRenderer.h"
#include "RigidBody2D.h"
#include "Collider.h"
#include "BoxCollider.h"
#include "CircleCollider.h"
#include "PolygonCollider.h"
#include "WheelJoint.h"
#include "ScriptableComponent.h"
#include "RevoluteJoint.h"
#include "CharacterMovementScript.h"
#include "CameraFollowScript.h"
#include "CivWaypointScript.h"
#include "TileMapper.h"
#include "VehicleController.h"
#endif !WS_COMPENENT_HEADERS_H